canciones = [
    """It'll take you all your time and your money but honey, you'll survive.""",
    """Liar!\nOh, nobody believes me.\nLiar!\nWhy don't you leave me alone?""",
    """Don't you hear my call though you're many years away?\nDon't you hear me calling you?""",
    """The bell that rings inside your mind is challenging the doors of time.\n(It's a kind of magic)""",
    """She came without a farthing.\nA babe without a name""",
    """All dead, all dead.\nAll the dreams we had and I wonder why I still live on.""",
    """Are you ready?\nHey, are you ready for this?\nAre you hanging on the edge of your seat?""",
    """Hey, I'm gonna get you too.\nAnother one bites the dust""",
    """It's all so beautiful, like a landscape painting in the sky, yeah!""",
    """I don't believe in Peter Pan, Frankenstein or Superman.""",
    """You say Rolls, I say Royce.\nYou say God, give me a choice!\nYou say Lord, I say, Christ!""",
    """You and me.\nWe are destined, you'll agree.\nTo spend the rest of our lives 
    with each other.\nThe rest of our days like two lovers.""",
    """Is this the real life? Is this just fantasy?""",
    """Mama, just killed a man.\nPut a gun against his head, pulled my trigger, now he's dead.""",
    """If I'm not back again this time tomorrow, carry on, carry on as if nothing really matters.""",
    """Mama, ooh.\nI don't wanna die.\nSometimes wish I'd never been born at all.""",
    """I see a little silhouetto of a man.\nScaramouche, Scaramouche, will you do the Fandango?""",
    """Beelzebub has a devil put aside for me, for me, for me!""",
    """So you think you can stone me and spit in my eye?\nSo you think you can love me and leave me to die?\n
    Oh, baby, can't do this to me, baby!""",
    """Nothing really matters, anyone can see.\nNothing really matters.\nNothing really matters to me.\n
    Any way the wind blows.""",
    """There goes my baby.\nShe knows how to rock 'n' roll.\nShe drives me crazy.""",
    """So dear friends your love is gone.\nOnly tears to dwell upon.""",
    """Kill joy, bad guy, big talking, small fry.\nYou're just an old barrow boy.\nHave you found a new toy 
    to replace me, can you face me?""",
    """Tonight I'm gonna have myself a real good time, I feel alive.""",
    """I'm a racing car passing by like Lady Godiva.\nI'm gonna go, go, go there's no stopping me.""",
    """Don't stop me now.\nI'm having such a good time.\nI'm having a ball.""",
    """Are you gonna take me home tonight?.\nOh, down beside that red firelight?""",
    """Fat bottomed girls, you make the rockin' world go 'round.""",
    """Flick of the wrist and you're dead baby.\nBlow him a kiss and you're mad.""",
    """Friends will be friends.\nWhen you're in need of love, they give you care and attention.""",
    """Come on and sit on my hot seat of love.\nAnd tell me how do you feel right after all.""",
    """Write my letter, feel much better.\nI’ll use my fancy patter on the telephone.""",
    """I can't live with you but I can't live without you.""",
    """I'm in love with my car.\nGot to feel for my automobile.""",
    """Through the sorrow, all through our splendor.\nDon't take offense at my innuendo.""",
    """Show yourself, destroy our fears, release your mask.""",
    """I don't want my freedom.\nThere's no reason for living with a broken heart.""",
    """I fell in love but now you say it's over and I'm falling apart.""",
    """I've fallen in love for the first time.\nAnd this time I know it's for real.""",
    """I was born to love you with every single beat of my heart.""",
    """"Let them eat cake," she says.\nJust like Marie Antoinette.""",
    """She's a Killer Queen.\nGunpowder, gelatin, dynamite with a laser beam.\n
    Guaranteed to blow your mind.""",
    """Las palabras de amor. Let me hear the words of love.""",
    """Ladies and gentlemen.\nI would like to say hello.\nAre you ready for some entertainment?\n
    Are you ready for a show?""",
    """Love of my life, you've hurt me.\nYou've broken my heart, and now you leave me.""",
    """Don't you misfire.\nFill me up with the desire to carry on.""",
    """All I want is the comfort and care.\nJust to know that my woman gives me sweet mother love.""",
    """My baby left me for somebody new.\nI don't wanna talk about it.\nWant to forget about it.\n
    Wanna be intoxicated with that special brew.""",
    """One man, one man.\nOne bar, one night.\nOne day, hey, hey\nJust gimme, gimme, gimme...\n
    fried chicken!""",
    """It's so easy when you know the rules.\nIt's so easy, all you have to do is fall in love.""",
    """And everything I had to know.\nI heard it on my radio.""",
    """Radio, someone still loves you.""",
    """Save me, save me, save me. I can't face this life alone.""",
    """Well you're just 17 all you want to do is disappear.\nYou know what I mean, t
    here's a lot of space between our ears.""",
    """Can anybody find me somebody to love?""",
    """Spread your wings and fly away.\nFly away, far away.""",
    """Teo Torriate konomama iko.\nAisuruhito yo.\nShizukana yoi ni.\nHikario tomoshi.\n
    Itoshiki oshieo idaki""",
    """You can't turn back the clock.\nYou can't turn back the tide, ain't that a shame?""",
    """The show must go on.\nInside my heart is breaking.\nMy makeup may be flaking 
    but my smile, still, stays on.""",
    """My soul is painted like the wings of butterflies.\nFairy tales of yesterday, 
    grow but never die.\nI can fly, my friends.""",
    """Tie your mother down, tie your mother down.\nLock your daddy out of doors, 
    I don't need him nosing around.""",
    """This is our last dance.""",
    """Can't we give ourselves one more chance?\nWhy can't we give love that one more chance?\n
    Why can't we give love, give love...""",
    """We are the champions, my friends.\nAnd we'll keep on fighting till the end.""",
    """We will, we will rock you.""",
    """Who wants to live forever?""",
    """Ooh, you make me live now, honey.""",
    """Look into my eyes and you'll see.\nI'm the only one.\nYou've captured my love, 
    stolen my heart, changed my life."""]